language: node_js

node_js:
  - node

install:
  - npm install

script:
  - npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)        || true
  - coveralls                 < coverage/lcov.info || true
  - codeclimate-test-reporter < coverage/lcov.info || true
