window.esdocSearchIndex = [
  [
    "@aureooms/js-uint64/src/add64.js~add64",
    "function/index.html#static-function-add64",
    "<span>add64</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/add64.js</span>",
    "function"
  ],
  [
    "@aureooms/js-uint64/src/and64.js~and64",
    "function/index.html#static-function-and64",
    "<span>and64</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/and64.js</span>",
    "function"
  ],
  [
    "@aureooms/js-uint64/src/big64.js~big64",
    "function/index.html#static-function-big64",
    "<span>big64</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/big64.js</span>",
    "function"
  ],
  [
    "@aureooms/js-uint64/src/compare.js~compare",
    "function/index.html#static-function-compare",
    "<span>compare</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/compare.js</span>",
    "function"
  ],
  [
    "@aureooms/js-uint64/src/get64.js~get64",
    "function/index.html#static-function-get64",
    "<span>get64</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/get64.js</span>",
    "function"
  ],
  [
    "@aureooms/js-uint64/src/limits.js~max",
    "variable/index.html#static-variable-max",
    "<span>max</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/limits.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-uint64/src/limits.js~min",
    "variable/index.html#static-variable-min",
    "<span>min</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/limits.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-uint64/src/mul64.js~mul64",
    "function/index.html#static-function-mul64",
    "<span>mul64</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/mul64.js</span>",
    "function"
  ],
  [
    "@aureooms/js-uint64/src/not64.js~not64",
    "function/index.html#static-function-not64",
    "<span>not64</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/not64.js</span>",
    "function"
  ],
  [
    "@aureooms/js-uint64/src/rotl64.js~rotl64",
    "function/index.html#static-function-rotl64",
    "<span>rotl64</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/rotl64.js</span>",
    "function"
  ],
  [
    "@aureooms/js-uint64/src/rotr64.js~rotr64",
    "function/index.html#static-function-rotr64",
    "<span>rotr64</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/rotr64.js</span>",
    "function"
  ],
  [
    "@aureooms/js-uint64/src/shl64.js~shl64",
    "function/index.html#static-function-shl64",
    "<span>shl64</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/shl64.js</span>",
    "function"
  ],
  [
    "@aureooms/js-uint64/src/shr64.js~shr64",
    "function/index.html#static-function-shr64",
    "<span>shr64</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/shr64.js</span>",
    "function"
  ],
  [
    "@aureooms/js-uint64/src/xor64.js~xor64",
    "function/index.html#static-function-xor64",
    "<span>xor64</span> <span class=\"search-result-import-path\">@aureooms/js-uint64/src/xor64.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/add64.js",
    "file/src/add64.js.html",
    "src/add64.js",
    "file"
  ],
  [
    "src/and64.js",
    "file/src/and64.js.html",
    "src/and64.js",
    "file"
  ],
  [
    "src/big64.js",
    "file/src/big64.js.html",
    "src/big64.js",
    "file"
  ],
  [
    "src/compare.js",
    "file/src/compare.js.html",
    "src/compare.js",
    "file"
  ],
  [
    "src/get64.js",
    "file/src/get64.js.html",
    "src/get64.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/limits.js",
    "file/src/limits.js.html",
    "src/limits.js",
    "file"
  ],
  [
    "src/mul64.js",
    "file/src/mul64.js.html",
    "src/mul64.js",
    "file"
  ],
  [
    "src/not64.js",
    "file/src/not64.js.html",
    "src/not64.js",
    "file"
  ],
  [
    "src/rotl64.js",
    "file/src/rotl64.js.html",
    "src/rotl64.js",
    "file"
  ],
  [
    "src/rotr64.js",
    "file/src/rotr64.js.html",
    "src/rotr64.js",
    "file"
  ],
  [
    "src/shl64.js",
    "file/src/shl64.js.html",
    "src/shl64.js",
    "file"
  ],
  [
    "src/shr64.js",
    "file/src/shr64.js.html",
    "src/shr64.js",
    "file"
  ],
  [
    "src/xor64.js",
    "file/src/xor64.js.html",
    "src/xor64.js",
    "file"
  ]
]